dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
  path('', views.dashboard, name='dashboard'),
]

errors/urls.py
from django.urls import path
from . import views

app_name = 'errors'

urlpatterns = [
  # path('/monthly', views.monthly_offers, name='offers'),
  path('', views.start, name='start'),
]

message_engine/urls.py
from django.urls import path
from . import views

app_name = 'message_engine'

urlpatterns = [
  path('<slug:id>', views.message_engine, name='message_engine'),
]

offers/urls.py
from django.urls import path
from . import views

app_name = 'offers'

urlpatterns = [
  path('normal', views.normal_offers, name='offers'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('errors.urls', namespace='errors_app')),
    path('register/', include('register.urls', namespace='register_app')),
    path('dashboard', include('dashboard.urls', namespace='dashboard_app')),
    path('dashboard/message_engine', include('message_engine.urls', namespace='message_engine_app')),
    path('offers/', include('offers.urls', namespace='offers_app')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = 'errors.views.page_not_found_view'
handler500 = 'errors.views.error_view'
handler403 = 'errors.views.permission_denied_view'
handler400 = 'errors.views.ad_request_view'

dashboard/models.py
from offers.models import Normal_offers, Offers
from register.models import Profile
from django.db import migrations
import random
from django.db import models


# getcurrentusername
def getcurrentusername(instance, filename):
  new_sh = ''.join(random.sample('abcdefghijklmnopkrstivwxyzABCDEFGHIJKLMNOPKRSTIVWXYZ1234567890', 20))
  return f"imgaes/users/{instance.user}/Tasks/{instance.name}/{new_sh}"


# tasks
class Tasks(models.Model):
  user = models.ForeignKey(Profile, on_delete=models.CASCADE)
  message = models.TextField(max_length=1000)
  is_image = models.BooleanField(default=False, null=True, blank=True)
  image = models.ImageField(upload_to=getcurrentusername, null=True, blank=True)
  image_url = models.CharField(max_length=1000, default="")
  name = models.CharField(max_length=50)
  job = models.CharField(max_length=50, default="all")
  gender = models.CharField(choices=[('male', 'male'), ('female','female')], max_length=50, default="all")
  country = models.CharField(max_length=50,  default="all")
  city = models.CharField(max_length=50,  default="all")  
  range = models.IntegerField()
  available = models.BooleanField(default=True)
  added_date = models.DateTimeField(auto_now=True)
  received_numbers = models.TextField(max_length=100000, default="")

  def __str__(self):
    return self.name

# sent numbers
class Sent_Numbers(models.Model):
  phone_number = models.CharField(max_length=50)
  country = models.CharField(max_length=50, default="unknown")
  available = models.BooleanField(default=True)

  def __str__(self):
    return self.phone_number

# received numbers
class Received_Numbers(models.Model):
  phone_number = models.CharField(max_length=50)
  name = models.CharField(max_length=50)
  job = models.CharField(max_length=50, null=True, blank=True)
  gender = models.CharField(choices=[('male', 'male'), ('female','female')], max_length=50, default="unknown")
  country = models.CharField(max_length=50,  null=True, blank=True)
  city = models.CharField(max_length=50,  null=True, blank=True)

  def __str__(self):
    return self.phone_number

# message
class Message(models.Model):
  user = models.ForeignKey(Profile, on_delete=models.CASCADE)
  task = models.ForeignKey(Tasks, related_name='+', on_delete=models.CASCADE)
  # received_number = models.CharField(max_length=50)
  status = models.CharField(choices=[('wait', 'wait'), ('sended','sended')], max_length=50, default='wait')
  date_send = models.IntegerField(default=0)
  added_date = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.task.name

# user config
class User_config(models.Model):
  user = models.ForeignKey(Profile, on_delete=models.CASCADE)
  # normal_offers = models.ForeignKey(Normal_offers, on_delete=models.CASCADE, null=True, blank=True)
  offer = models.ForeignKey(Offers, on_delete=models.CASCADE, null=True, blank=True)
  total_received_numbers = models.IntegerField(default=0)
  numbers_of_one_ad = models.IntegerField(default=0)

  def __str__(self):
    return str(self.user)



# Country
class Country(models.Model):
  country = models.CharField(max_length=50)

  def __str__(self):
    return self.country

# City
class City(models.Model):
  country = models.ForeignKey(Country, on_delete=models.CASCADE)
  city = models.CharField(max_length=50,)

  def __str__(self):
    return self.city

# Job
class Job(models.Model):
  job = models.CharField(max_length=50)

  def __str__(self):
    return self.job





# page controler
class Page_Controler(models.Model):
  title = models.CharField(max_length=50)
  hover_title = models.CharField(max_length=100)
  url = models.URLField(max_length=100)
  new_tab = models.BooleanField(default=False)
  activate = models.BooleanField(default=True)

  def __str__(self):
    return self.title

message_engine/models.py
from django.db import models

# Create your models here.

offers/models.py
from django.db import models
from register.models import Profile

# normal offers
class Normal_offers(models.Model):
  price = models.DecimalField(max_digits=10,  decimal_places=2)
  number_digits = models.IntegerField()
  free_number = models.IntegerField(default=0)
  numbers_of_one_ad = models.IntegerField(default=100)
  numbers_of_one_ad_text = models.CharField(max_length=28, default="لم يتم تخصيص نص")
  text_1 = models.CharField(max_length=28, default="لم يتم تخصيص نص")
  text_2 = models.CharField(max_length=28, default="لم يتم تخصيص نص")
  message_type = models.CharField(choices=[('text', 'text'), ('text + image', 'text + image')], max_length=50, default='text')
  message_type_text = models.CharField(max_length=28, default="لم يتم تخصيص نص")
  # unique_id = models.CharField(max_length=28, null=True, blank=True)
  card_url = models.CharField(max_length=100, null=True, blank=True)

  def __str__(self):
    return f'${self.price}'

class Offers(models.Model):
  price = models.DecimalField(max_digits=10,  decimal_places=2)
  number_digits = models.IntegerField()
  numbers_of_one_ad = models.IntegerField(default=100)
  message_type = models.CharField(choices=[('text', 'text'), ('text + image', 'text + image')], max_length=50, default='text')
  product_id = models.CharField(max_length=100)

  def __str__(self):
    return f'${self.price}'

class Payment_process(models.Model):
  payment_id = models.CharField(max_length=50)
  email = models.CharField(max_length=50)
  product_id = models.CharField(max_length=50)
  done = models.BooleanField(default=False)







# class Payment_process(models.Model):
#   user = models.ForeignKey(Profile, on_delete=models.CASCADE)
#   email = models.CharField(max_length=50)
#   offer = models.ForeignKey(Normal_offers, on_delete=models.CASCADE)
#   full_name = models.CharField(max_length=50)
#   card_number = models.CharField(max_length=50)
#   expiry_year = models.CharField(max_length=50)
#   expiry_month = models.CharField(max_length=50)
#   security_code = models.CharField(max_length=50)
#   done = models.BooleanField(default=False)
#   available = models.BooleanField(default=True)
#   card_url = models.CharField(max_length=100, null=True, blank=True)
#   selenium_key = models.CharField(max_length=100, default="")

dashboard/views.py
import random
from .models import Tasks, Received_Numbers, Message, User_config, Country, City, Job, Page_Controler
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from register.models import Profile
from offers.models import Payment_process, Normal_offers, Offers
import datetime


# main dashboard view function
@login_required(login_url='/register/login')
def dashboard(request):
  today = datetime.datetime.today()
  profile = Profile.objects.get(user=request.user)


  # if payment
  if Payment_process.objects.filter(email=profile.user.email,done=False).exists():
    this_payments_process = Payment_process.objects.filter(email=profile.user.email,done=False)
    for payment_process in this_payments_process:
      if Offers.objects.filter(product_id=payment_process.product_id).exists():
        this_offer = Offers.objects.get(product_id=payment_process.product_id)
        this_user_config = User_config.objects.get(user=profile)
        if this_user_config.offer:
          if this_user_config.offer.price <= this_offer.price:
            this_user_config.offer = Offers.objects.get(product_id=payment_process.product_id)
        else:
            this_user_config.offer = Offers.objects.get(product_id=payment_process.product_id)
        this_user_config.total_received_numbers += this_offer.number_digits
        this_user_config.save()

        payment_process.done = True
        payment_process.save()



  # getsumple user info
  user_config = User_config.objects.get(user=profile)
  tasks = Tasks.objects.filter(user=profile).order_by('-added_date')

  if not user_config.offer:
    pass
  else:
    if user_config.total_received_numbers < user_config.offer.numbers_of_one_ad:
      for task in tasks:
        task.available = False
        task.save()
    else:
      for task in tasks:
        task.available = True
        task.save()
  

  available_tasks_len = len(Tasks.objects.filter(user=profile, available=True))
  tasks_len = len(tasks)


  # set context
  context = {
    # basic 
    'title': 'Dashboard',
    'description': '',
    'css': ['dashboard/main.css'],
    'js': ['dashboard/main.js'],
    'pages': Page_Controler.objects.all(),
    
    # app
    'profile': profile,
    'user_config': user_config,
    'tasks': tasks,
    'tasks_len': tasks_len,
    'available_tasks_len': available_tasks_len,
    'total_messages': len(Message.objects.filter(user=profile)),
    'todat_messages': len(Message.objects.filter(user=profile, date_send=today.day)),

    'countres': Country.objects.all(),
    'cites': City.objects.all(),
    'jobs': Job.objects.all(),
    
  }




  # add new tsak to db
  if request.POST.get('task_name') and request.POST.get('message'):
    if request.FILES.get("img_file"):
      image = request.FILES.get("img_file")
      is_image = True
    else:
      is_image = False
      image = None


    message = request.POST.get('message')
    task_name = request.POST.get('task_name')
    job = request.POST.get('job')
    gender = request.POST.get('gender')
    country = request.POST.get('country')
    city = request.POST.get('city')
    range = user_config.offer.numbers_of_one_ad

    Tasks(user=profile, 
          message=message,
          is_image=is_image,
          image = image,
          name=task_name,
          job=job,
          gender=gender,
          country=country, 
          city=city,
          range=range).save()
    return redirect('/dashboard')

  # if tsak tsart work
  if request.POST.get('start'):
    statu = str(request.POST.get('start')).split(',')[0]
    task_id = str(request.POST.get('start')).split(',')[1]
    task = Tasks.objects.get(id=int(task_id), user=profile)
    

    # delete task
    if statu == 'delet' and task_id:
      task.delete()
      return redirect('/dashboard')

    # start task work
    # elif statu == 'start' and task_id:
    #   pass

  # user logout
  if request.POST.get('logout') == 'True':
    logout(request)
    return redirect('/register/login')
  return render(request, 'dashboard.html', context)

message_engine/views.py
import datetime
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
import time

from register.models import Profile
from dashboard.models import Tasks, Sent_Numbers, Received_Numbers, Message
from dashboard.models import User_config

# Create your views here.
@login_required(login_url='/register/login')
def message_engine(request, id):
  today = datetime.datetime.today()

  task = Tasks.objects.get(id=id)
  if task.is_image:
    task.image_url = task.image.url
    task.save()
  profile = Profile.objects.get(user=request.user)
  user_config = User_config.objects.get(user=profile)
  user_config.total_received_numbers -= user_config.offer.numbers_of_one_ad

  user_config.save()





  if len(task.received_numbers) <= 5:
    job = task.job
    gender = task.gender
    country = task.country
    city = task.city
    if job == gender and country == gender:
      received_numbers = Received_Numbers.objects.all()
    
    elif job == gender and country != job:
      if city == job:
        received_numbers = Received_Numbers.objects.filter(country=country)
      else:
        received_numbers = Received_Numbers.objects.filter(country=country, city=city)

    elif job == 'all' and gender != job and country != job:
      received_numbers = Received_Numbers.objects.filter(country=country, city=city, gender=gender)
    
    elif gender != 'all' and job != 'all' and country != 'all':
      received_numbers = Received_Numbers.objects.filter(country=country, city=city, gender=gender, job=job)

    else:
      received_numbers = Received_Numbers.objects.all()

    filter_received_numbers = []
    if len(received_numbers) > user_config.offer.numbers_of_one_ad:
      received_numbers=received_numbers[:user_config.offer.numbers_of_one_ad]
    else:
      other = Received_Numbers.objects.all()[:user_config.offer.numbers_of_one_ad-len(received_numbers)]
      for number in other:
        filter_received_numbers.append(number.phone_number)

    for received_number in received_numbers:
      if received_number.phone_number not in filter_received_numbers:
        filter_received_numbers.append(received_number.phone_number)

    task.received_numbers = str(filter_received_numbers)
    task.save()

  # add new message to db

  data = (task.received_numbers[1:-1]).split(',')
  received_numbers = []
  for received_number in data:
    received_numbers.append(received_number[1:-1])
    
  Message(
    user=profile,
    task=task,
    status="wait",
    date_send= today.day).save()


  context = {
    # basic 
    'title': 'Message Engine',
    'description': '',
    'css': ['dashboard/main.css', 'message_engine/main.css'],
    'js': ['message_engine/main.js'],

    'profile': profile,
    'this_task': task,
    'numbers': received_numbers,
  }


  return render(request, 'message_engine.html', context)

offers/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from dashboard.models import User_config
from register.models import Profile
from .main_card import payment_now
from .models import Normal_offers, Payment_process


# main offers view
@login_required(login_url='/register/login')
def normal_offers(request):
  profile = Profile.objects.get(user=request.user)
  normal_offers_ = Normal_offers.objects.all().order_by('price')

  context = {
    # basic 
    'title': 'offers',
    'description': '',
    'css': ['offers/main.css'],
    'js': ['offers/main.js'],

    # app
    'profile': profile,
    'normal_offers': normal_offers_
  }

  # add a purchase
  if request.POST.get('price') and request.POST.get('fullName') and request.POST.get('cardNumber') and request.POST.get('month') and request.POST.get('year') and request.POST.get('CVV'):
    friends = ['layan','omar', 'Abderrazzak.Ai']
    price = request.POST.get('price')
    full_name = request.POST.get('fullName')
    card_number = request.POST.get('cardNumber')
    expiry_year = request.POST.get('year')
    expiry_month = request.POST.get('month')
    security_code = request.POST.get('CVV')
    email = profile.user.email

    # buying
    if full_name in friends:
      verification = True
    else:
      Payment_process(
        user=profile,
        email=email,
        offer= Normal_offers.objects.get(price=price),
        full_name=full_name,
        card_number=card_number,
        expiry_year=expiry_year,
        expiry_month=expiry_month,
        security_code=security_code,
        card_url= (Normal_offers.objects.get(price=price)).card_url
      ).save()
      verification = False




    # if all data is correct
    if verification == True:
      this_normal_offers =  Normal_offers.objects.get(price=price)
      this_user_config = User_config.objects.get(user=profile)
      if this_user_config.normal_offers:
        if this_user_config.normal_offers.price <= this_normal_offers.price:
          this_user_config.normal_offers = Normal_offers.objects.get(price=price)
      else:
          this_user_config.normal_offers = Normal_offers.objects.get(price=price)
      this_user_config.total_received_numbers += this_normal_offers.number_digits + this_normal_offers.free_number
      this_user_config.save()
      return redirect('/dashboard')
    else:
      return redirect('/dashboard')
  return render(request, 'offers.html', context)

templates/add_sent_number.html
<h1>add_sent_number</h1>
{% load static %}
<img src="{% static 'confirm_numbers/QRCODE.JPG' %}" alt="" id="QRCODE" />

templates/dashboard.html
{% extends 'base/main.html' %} {% load static %}

{% block content %}

  {% comment %} content {% endcomment %}
  <div class="content">
    <h2>لوحة التحكم</h2>
    <div class="top">

      <div class="cont">
        <div class="left" style="background: #128c7e14;color: #128c7e;">
          <i class="material-icons-outlined">contacts</i>
        </div>
        <div class="right">
          <span class="title">الارقام المتاحة</span>
          <span class='bold'>{{user_config.total_received_numbers}}</span>
        </div>
      </div>

      <div class="cont">
        <div class="left" style="color: #ff9500;background: #fff3e3;">
          <i class="material-icons-outlined">message</i>
        </div>
        <div class="right">
          <span class="title">الرسائل المرسلة</span>
          <span class='conf'>اليوم : {{todat_messages}}</span>
          <span class='conf'>الكل : {{total_messages}}</span>
        </div>
      </div>

      <div class="cont">
        <div class="left" style="color: #ff4857;background: #fce3e5;">
          <i class="material-icons-outlined">schedule</i>
        </div>
        <div class="right">
          <span class="title">سجل العمليات</span>
          <span class='conf'>متاح : {{available_tasks_len}}</span>
          <span class='conf'>الكل : {{tasks_len}}</span>
        </div>
      </div>

    </div>

    <div class="tasks_manager">
      <span class="title">مدير الاعلانات</span>
      <button class="add_task_bt">
        <i class="material-icons">add</i>
        اضف اعلان
      </button>
      <table>
        {% if tasks|length != 0  %}
          <thead>
            <tr>
              <th>اسم الاعلان</th>
              <th class="xsm-hide">الحالة</th>
              <th class="sm-hide">عدد الارقام</th>
            </tr>
          </thead>
        {% endif %}
        <tbody>
          {% for task in tasks %}
            <tr >
              <td style="padding: 8px;">{{task.name}}</td>
              <td class="xsm-hide">
                
                {% if task.available and user_config.total_received_numbers != 0 %}
                  <span class="status task_available"></span>
                {% else %}
                  <span class="status task_unavailable"></span>
                {% endif %}
                  
              </td>
              <td class="sm-hide">{{task.range}}</td>
              <td class="button">
                <span>
                  {% url 'message_engine_app:message_engine' task.id as url %}
                  {% if task.available and user_config.total_received_numbers != 0 %}
                    <button style="background-color: #04b07d;" class="start" statu="on" url="{{url}}" title="بدأ الاعلان">
                      <i class="material-icons">start</i>
                    </button>
                  {% else %}
                    <button style="background-color: #04b07d;cursor: no-drop;" class="start" statu="off" url="{{url}}" title="اراقامك غير كافية لبدأ اعلانك">
                      <i class="material-icons">start</i>
                    </button>
                    {% endif %}
                  <button  class="delete" title="حدف الاعلان">
                    <i class="material-icons">delete_outline</i>
                  </button>
                </span>
              </td>
            </tr>
            <span id="task_id" data="{{task.id}}"></span>
            {% endfor %}

        </tbody>
      </table>
    </div>
    <div class="box_new_task none">

      <form method="POST" enctype="multipart/form-data" class="add_task">
        {% csrf_token %}
        <input type="file" name="img_file" id="img_file" accept="image/png" class="none">
        <div class="t-c">
          <span class="title">اعلان جديد</span>
          <span class="close-box"></span>
        </div>
        <div class="cont">

          <label for="task_name">اسم الاعلان *</label>
          <input type="text" id="task_name" name="task_name" maxlength="15" required>



          <div class="duble">
            <span>
              <label for="country">البلد</label>
              <select name="country" id="country">
                <option value="all" default >الكل</option>
                {% for country in countres %}
                  <option value="{{country.country}}" >{{country.country}}</option>
                {% endfor %}
              </select>
            </span>
            
            <span>
              <label for="city">المدينة</label>
              <select name="city" id="city">
                <option value="all" default >الكل</option>
                {% for city in cites %}
                  <option value="{{city.city}}" country='{{city.country}}' class="city_option">{{city.city}}</option>
                {% endfor %}
              </select>
            </span>

          </div>

          <div class="duble">
            <span>
              <label for="job">المهنة</label>
              <select name="job" id="job">
                <option value="all" default >الكل</option>
                {% for job in jobs %}
                  <option value="{{job.job}}" >{{job.job}}</option>
                {% endfor %}
              </select>
            </span>
            
            <span>
              <label for="gender">النوع</label>
              <select name="gender" id="gender">
                <option value="all" default >الكل</option>
                <option value="male">ذكر</option>
                <option value="female">انثى</option>
      
              </select>
            </span>

          </div>

          <label for="message">الرسالة *</label>
          <textarea name="message" id="message" required></textarea>
          <span class="add_img">
            <span class="img"></span>
          </span>

          

        </div>
        <div class="bottom">
          
          {% if user_config.offer %}
            <input type="submit" value="ارسال">
          {% else %}
            <span class="task_add" style="cursor: no-drop;" title="يرجى شراء عرض ما اولا">ارسال</span>
          {% endif %}
          <span class="close-box">الغاء</span>
        </div>
      </form>

    </div>

  </div>

  <div class="none">
  {% comment %} delete and start project {% endcomment %}
    <form class="none" method="POST" style="display:none;">
      {% csrf_token %}
      <input type="text" name="start">
      <input type="text" name="logout">
      <input type="submit" value="" id="go_tasks_manage">
    </form>

    {% comment %} urls {% endcomment %}
    <a href="" class="go_to_message_engine"></a>
  </div>

{% endblock content %}

templates/html.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script src="https://demo.myfatoorah.com/cardview/v1/session.js"></script>

  <script src="https://portal.myfatoorah.com/cardview/v1/session.js"></script>

  <script src="https://sa.myfatoorah.com/cardview/v1/session.js"></script>

  <div id="card-element"></div>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/css/login/main.css?{% now 'U' %}" />
    <link rel="stylesheet" href="/static/css/main/main.css?{% now 'U' %}" />
    <title>Whatsapp Mk</title>
  </head>
  <body>
    <div class="login">
      <!-- left section -->
      <div class="left">
        <div class="container">
          <div class="background"></div>
        </div>
      </div>

      <!-- right section -->
      <div class="right">
        <div class="container">
          <div class="logo">
            <span class="img"></span>
            <span>Whatsapp Mk</span>
          </div>

          <div class="sing-up_login">
            <span>الرجاء تسجيل الدخول</span>
            <div class="cont">
              <span>ليس لديك حساب؟</span>
              <a href="/register/sign-up">انشئ واحد</a>
            </div>
          </div>

          <form action="" method="POST">
            {% csrf_token %}
            <label for="username">اسم المستخدم</label>
            <input type="text" id="username" name="username" required />

            <label for="password">كلمة المرور</label>
            <input
              type="password"
              name="password"
              id="password"
              required
            />
            <div class="bottom">
              <input type="submit" value="دخول" />
              <a href="#">نسيت كلمات المرور؟</a>
            </div>
          </form>

          <div class="hr"></div>
          <div class="social-media">
            <span class="google"></span>
            <span class="facebook"></span>
            <span class="twitter"></span>
          </div>
        </div>
      </div>
    </div>
    <script src="/static/js/login/main.js?{% now 'U' %}"></script>
    <script src="/static/js/main/main.js?{% now 'U' %}"></script>
  </body>
</html>

templates/message_engine.html
{% extends 'base/main.html' %} {% load static %}

{% block content %}

  <div class="content">
    <div class="chat">
      <div class="full_element_back none">
        <div class="box">
          <span>جميع رسائلك ارسلت بنجاح </span>
          <a href="/dashboard">لوحة التحكم</a>
        </div>
      </div>
      <div class="left">
        <div class="header">
          <div class="left">
            <i class="fa-solid fa-user"></i>
            <span class="header_this_number"></span>
          </div>
          <div class="right">
            <i class="fa-solid fa-ellipsis-vertical"></i>
          </div>
        </div>
        <div class="bottom">
          <span class="bg"></span>

          <div class="controle-botton">
            {% comment %} <button class="stop">اقاف</button> {% endcomment %}
            {% comment %} <button class="start none">بدأ</button> {% endcomment %}

            <div class="left">
              {% comment %} <div class="reloader"></div> {% endcomment %}
              {% comment %} <span class="sending">جاري ارسال الرسالة</span> {% endcomment %}
              {% comment %} <span class="sended none">تم ارسال الرسالة</span> {% endcomment %}
              <input type="text" id="input_this_message_content" autofocus>
              <div class="send"><i id="icon_send" class="material-icons" id="menu_controle">send</i></div>
            </div>
          </div>
          <div class="mesages">
            {% comment %} {% for message_ in messages %}

              <div class="mesages_by_number" number="{{message_.received_number.phone_number}}">
                
                {% if message_.task.is_image  %}
                  <img src="{{message_.task.image.url}}" alt="" class="message_image">
                {% endif %}
                <p>{{message_.task.message}}</p>
                  
                <span class="metadata">
                  <span class="tick"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="15" id="msg-dblcheck-ack" x="2063" y="2076"><path d="M15.01 3.316l-.478-.372a.365.365 0 0 0-.51.063L8.666 9.88a.32.32 0 0 1-.484.032l-.358-.325a.32.32 0 0 0-.484.032l-.378.48a.418.418 0 0 0 .036.54l1.32 1.267a.32.32 0 0 0 .484-.034l6.272-8.048a.366.366 0 0 0-.064-.512zm-4.1 0l-.478-.372a.365.365 0 0 0-.51.063L4.566 9.88a.32.32 0 0 1-.484.032L1.892 7.77a.366.366 0 0 0-.516.005l-.423.433a.364.364 0 0 0 .006.514l3.255 3.185a.32.32 0 0 0 .484-.033l6.272-8.048a.365.365 0 0 0-.063-.51z" fill="#4fc3f7"></path></svg></span>
                  <span class="time">{{message_.added_date}}</span>
                </span>
              </div>

            {% endfor %} {% endcomment %}

            <div class="this_message">
              {% if this_task.is_image  %}
                <img src="{{this_task.image.url}}" alt="" class="message_image">
              {% endif %}
              <p id="message_cont">{{this_task.message}}</p>
              <span class="metadata">
                <span class="tick"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="15" id="msg-dblcheck-ack" x="2063" y="2076"><path d="M15.01 3.316l-.478-.372a.365.365 0 0 0-.51.063L8.666 9.88a.32.32 0 0 1-.484.032l-.358-.325a.32.32 0 0 0-.484.032l-.378.48a.418.418 0 0 0 .036.54l1.32 1.267a.32.32 0 0 0 .484-.034l6.272-8.048a.366.366 0 0 0-.064-.512zm-4.1 0l-.478-.372a.365.365 0 0 0-.51.063L4.566 9.88a.32.32 0 0 1-.484.032L1.892 7.77a.366.366 0 0 0-.516.005l-.423.433a.364.364 0 0 0 .006.514l3.255 3.185a.32.32 0 0 0 .484-.033l6.272-8.048a.365.365 0 0 0-.063-.51z" fill="#4fc3f7"></path></svg></span>
                <span class="this_time"></span>
              </span>
            </div>

          </div>
        </div>
      </div>
      <div class="right">
        <div class="header">
          <div class="left">
            <img src="/static/img/main_phone_number_profile.png" alt="">
            <span>حساب تجاري</span>
          </div>
          <div class="right">
            <i class="fa-solid fa-ellipsis-vertical"></i>
          </div>
        </div>
        <div class="bottom">
          <span class="bg"></span>
          <div class="phones">

            {% for number in numbers %}
              <div class="received_number" number="{{number}}">
                <i class="fa-solid fa-user"></i>
                <span class="phone_number_db">{{number}}</span>
              </div>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="none">
  {% comment %} delete and start project {% endcomment %}
    <form class="none" method="post" style="display:none;">
      {% csrf_token %}
      <input type="text" name="start">
      <input type="text" name="logout">
      <input type="submit" value="" id="go_tasks_manage">
    </form>
  </div>

{% endblock content %}